"""
LogiPredict AI - Simulation Workspace & Stress Testing ORM Models
=================================================================
Models for multi-echelon disruption scenarios, discrete-event simulation runs,
7-dimension comparative metrics, resilience scores, and automated mitigations.
"""

from datetime import datetime
from typing import List, Optional
from sqlalchemy import (
    Integer,
    String,
    Float,
    Boolean,
    DateTime,
    Text,
    ForeignKey,
    Index,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.base import Base


class SimulationScenarioModel(Base):
    """
    Configured stress test disruption scenario (weather, route block, demand surge, etc.).
    """
    __tablename__ = "simulation_scenarios"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    scenario_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    scenario_name: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    disruption_type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(32), default="HIGH", nullable=False)
    duration_days: Mapped[int] = mapped_column(Integer, default=7, nullable=False)
    affected_nodes_json: Mapped[str] = mapped_column(Text, default="[]", nullable=False)
    parameters_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    runs: Mapped[List["SimulationRunModel"]] = relationship(
        "SimulationRunModel",
        back_populates="scenario",
        cascade="all, delete-orphan",
    )


class SimulationRunModel(Base):
    """
    Execution trace of a discrete-event simulation run under a given scenario.
    """
    __tablename__ = "simulation_runs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    scenario_id: Mapped[str] = mapped_column(
        String(64),
        ForeignKey("simulation_scenarios.scenario_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    status: Mapped[str] = mapped_column(String(32), default="COMPLETED", nullable=False)
    resilience_score: Mapped[float] = mapped_column(Float, default=100.0, nullable=False)
    stockout_events_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    cost_impact_inr: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    delivery_delay_hours: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    baseline_metrics_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    simulated_metrics_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Relationships
    scenario: Mapped["SimulationScenarioModel"] = relationship(
        "SimulationScenarioModel",
        back_populates="runs",
    )
    recommendations: Mapped[List["SimulationRecommendationModel"]] = relationship(
        "SimulationRecommendationModel",
        back_populates="run",
        cascade="all, delete-orphan",
    )


class SimulationRecommendationModel(Base):
    """
    Automated mitigation actions generated by simulation engine runs.
    """
    __tablename__ = "simulation_recommendations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    recommendation_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    run_id: Mapped[str] = mapped_column(
        String(64),
        ForeignKey("simulation_runs.run_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(128), nullable=False)
    recommendation_type: Mapped[str] = mapped_column(String(64), nullable=False)
    priority: Mapped[str] = mapped_column(String(32), default="HIGH", nullable=False)
    action_payload_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    estimated_resilience_boost: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    status: Mapped[str] = mapped_column(String(32), default="PENDING", nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    run: Mapped["SimulationRunModel"] = relationship(
        "SimulationRunModel",
        back_populates="recommendations",
    )
