"""
LogiPredict AI - Synthetic Historical Demand Generator
======================================================
Phase 5.2: Forecasting Engine Data Generator
Indian Army Forward Supply Chain (SIH 2026)

Generates reproducible, realistic synthetic historical demand and stock series
across military supply categories and forward storage locations.

DISCLAIMER: All data generated by this module is synthetic and intended solely
for research, testing, simulation, and demonstration purposes. It does not represent
actual military operational logs, stock levels, or classified tactical intelligence.
"""

from datetime import datetime, timedelta
import math
import random
from typing import Dict, List, Any, Optional
import pandas as pd


# Baseline simulation reference date
BASE_SIMULATION_DATE = datetime(2026, 10, 2, 0, 0, 0)
DEFAULT_RANDOM_SEED = 42

# Domain SKU Reference Catalog with baseline consumption rates and storage limits
SKU_CATALOG: Dict[str, Dict[str, Any]] = {
    "SKU-POL-DSL-01": {
        "item_id": "SKU-POL-DSL-01",
        "name": "Winter-Grade Diesel ATF-800",
        "category": "POL (Fuel & Lubricants)",
        "unit": "Liters",
        "base_daily": 3200.0,
        "std_dev_ratio": 0.12,
        "seasonal_factor": 0.25,  # Higher in colder months (winter preparation)
        "current_stock": 84000.0,
        "max_capacity": 150000.0,
        "min_threshold": 15000.0,
        "reorder_level": 30000.0,
    },
    "SKU-POL-KRS-02": {
        "item_id": "SKU-POL-KRS-02",
        "name": "High-Altitude Kerosene SKO",
        "category": "POL (Fuel & Lubricants)",
        "unit": "Liters",
        "base_daily": 1800.0,
        "std_dev_ratio": 0.14,
        "seasonal_factor": 0.35,  # High altitude heating (Bukhari stoves)
        "current_stock": 24000.0,
        "max_capacity": 60000.0,
        "min_threshold": 6000.0,
        "reorder_level": 12000.0,
    },
    "SKU-ORD-556-03": {
        "item_id": "SKU-ORD-556-03",
        "name": "5.56x45mm INSAS Ball Ammunition",
        "category": "Ammunition & Ordnance",
        "unit": "Tins",
        "base_daily": 12.0,
        "std_dev_ratio": 0.30,
        "seasonal_factor": 0.05,
        "current_stock": 650.0,
        "max_capacity": 2000.0,
        "min_threshold": 100.0,
        "reorder_level": 250.0,
    },
    "SKU-ORD-81M-04": {
        "item_id": "SKU-ORD-81M-04",
        "name": "81mm Mortar High-Explosive Shells",
        "category": "Ammunition & Ordnance",
        "unit": "Crates",
        "base_daily": 8.0,
        "std_dev_ratio": 0.35,
        "seasonal_factor": 0.05,
        "current_stock": 420.0,
        "max_capacity": 1200.0,
        "min_threshold": 60.0,
        "reorder_level": 150.0,
    },
    "SKU-ORD-155-08": {
        "item_id": "SKU-ORD-155-08",
        "name": "155mm Bofors High-Explosive Extended Range",
        "category": "Ammunition & Ordnance",
        "unit": "Shells",
        "base_daily": 15.0,
        "std_dev_ratio": 0.28,
        "seasonal_factor": 0.04,
        "current_stock": 880.0,
        "max_capacity": 2500.0,
        "min_threshold": 120.0,
        "reorder_level": 300.0,
    },
    "SKU-RAT-MRE-05": {
        "item_id": "SKU-RAT-MRE-05",
        "name": "High-Altitude 24hr Combat Rations (MRE)",
        "category": "Combat Rations & MREs",
        "unit": "Packs",
        "base_daily": 450.0,
        "std_dev_ratio": 0.09,
        "seasonal_factor": 0.10,
        "current_stock": 14200.0,
        "max_capacity": 30000.0,
        "min_threshold": 2500.0,
        "reorder_level": 5000.0,
    },
    "SKU-RAT-WTR-09": {
        "item_id": "SKU-RAT-WTR-09",
        "name": "Mineralized Potable Water Cans (20L)",
        "category": "Combat Rations & MREs",
        "unit": "Cans",
        "base_daily": 120.0,
        "std_dev_ratio": 0.08,
        "seasonal_factor": 0.15,
        "current_stock": 3800.0,
        "max_capacity": 10000.0,
        "min_threshold": 800.0,
        "reorder_level": 1800.0,
    },
    "SKU-MED-PLM-07": {
        "item_id": "SKU-MED-PLM-07",
        "name": "Freeze-Dried Plasma & Vaccines",
        "category": "Cold-Chain Medical & Vaccines",
        "unit": "Kits",
        "base_daily": 6.0,
        "std_dev_ratio": 0.25,
        "seasonal_factor": 0.08,
        "current_stock": 120.0,
        "max_capacity": 400.0,
        "min_threshold": 25.0,
        "reorder_level": 50.0,
    },
    "SKU-MED-TRM-10": {
        "item_id": "SKU-MED-TRM-10",
        "name": "High-Altitude Combat Trauma Packs",
        "category": "Cold-Chain Medical & Vaccines",
        "unit": "Packs",
        "base_daily": 10.0,
        "std_dev_ratio": 0.20,
        "seasonal_factor": 0.05,
        "current_stock": 260.0,
        "max_capacity": 800.0,
        "min_threshold": 40.0,
        "reorder_level": 90.0,
    },
    "SKU-ENG-BAT-11": {
        "item_id": "SKU-ENG-BAT-11",
        "name": "Extreme-Cold Heavy Duty Gel Batteries",
        "category": "Spares & Engineering",
        "unit": "Units",
        "base_daily": 5.0,
        "std_dev_ratio": 0.22,
        "seasonal_factor": 0.30,  # Cold weather battery degradation
        "current_stock": 140.0,
        "max_capacity": 500.0,
        "min_threshold": 20.0,
        "reorder_level": 45.0,
    },
    "SKU-ENG-TRK-12": {
        "item_id": "SKU-ENG-TRK-12",
        "name": "Heavy Transport Track Links & Pins",
        "category": "Spares & Engineering",
        "unit": "Sets",
        "base_daily": 3.0,
        "std_dev_ratio": 0.30,
        "seasonal_factor": 0.12,
        "current_stock": 95.0,
        "max_capacity": 300.0,
        "min_threshold": 15.0,
        "reorder_level": 30.0,
    },
    "SKU-GEN-ECW-06": {
        "item_id": "SKU-GEN-ECW-06",
        "name": "Extreme Cold Weather Clothing (ECWCS)",
        "category": "General Stores & Winter Gear",
        "unit": "Sets",
        "base_daily": 25.0,
        "std_dev_ratio": 0.18,
        "seasonal_factor": 0.40,  # High winter surge
        "current_stock": 820.0,
        "max_capacity": 2500.0,
        "min_threshold": 100.0,
        "reorder_level": 250.0,
    },
}

# Storage Locations (Forward Depots and Staging Hubs)
DEPOT_CATALOG: Dict[str, Dict[str, Any]] = {
    "DEPOT-LEH-01": {"name": "Leh Forward Logistics Hub", "elevation_ft": 11500, "weight": 1.0},
    "DEPOT-KGL-02": {"name": "Kargil Sector Supply Point", "elevation_ft": 8780, "weight": 0.75},
    "DEPOT-DRA-03": {"name": "Dras Sub-Sector Buffer Depot", "elevation_ft": 10800, "weight": 0.60},
    "DEPOT-SNM-04": {"name": "Sonamarg Staging Transit Camp", "elevation_ft": 8960, "weight": 0.50},
    "DEPOT-NYM-05": {"name": "Nyoma Advanced Landing Ground", "elevation_ft": 13700, "weight": 0.40},
    "DEPOT-DIS-06": {"name": "Diskit / Nubra Base Logistics Depot", "elevation_ft": 10300, "weight": 0.45},
}


class SyntheticDemandGenerator:
    """
    Generates deterministic, realistic daily demand time-series data for testing and validation.

    Attributes:
        seed (int): Fixed random seed for deterministic reproduction.
        base_date (datetime): Reference date representing 'today' in the simulation.
    """

    def __init__(self, seed: int = DEFAULT_RANDOM_SEED, base_date: datetime = BASE_SIMULATION_DATE):
        self.seed = seed
        self.base_date = base_date

    def get_sku_metadata(self, item_id: str) -> Optional[Dict[str, Any]]:
        """Returns catalog entry for a specific SKU or None if not found."""
        return SKU_CATALOG.get(item_id)

    def get_all_skus(self) -> List[Dict[str, Any]]:
        """Returns all registered SKU catalog entries."""
        return list(SKU_CATALOG.values())

    def get_all_depots(self) -> List[Dict[str, Any]]:
        """Returns all registered storage depot locations."""
        return [{"depot_id": k, **v} for k, v in DEPOT_CATALOG.items()]

    def generate_daily_demand_series(
        self,
        item_id: str = "SKU-POL-DSL-01",
        depot_id: str = "all",
        days: int = 90,
        start_offset_days: int = -90,
    ) -> pd.DataFrame:
        """
        Generates a chronological daily time-series DataFrame for a specified SKU and depot.

        Args:
            item_id: Target SKU identifier or 'all' for aggregated demand.
            depot_id: Target depot identifier or 'all'.
            days: Number of daily data points to generate.
            start_offset_days: Offset relative to base_date for the first data point.

        Returns:
            pd.DataFrame with columns ['date', 'timestamp', 'item_id', 'item_name',
                                       'category', 'location_id', 'location_name',
                                       'unit', 'demand', 'is_synthetic', 'data_source']
        """
        rng = random.Random(self.seed + hash(f"{item_id}_{depot_id}"))

        sku_list = [SKU_CATALOG[item_id]] if item_id in SKU_CATALOG else (
            list(SKU_CATALOG.values()) if item_id == "all" else [SKU_CATALOG["SKU-POL-DSL-01"]]
        )

        depot_list = (
            [{"id": depot_id, **DEPOT_CATALOG[depot_id]}]
            if depot_id in DEPOT_CATALOG
            else [{"id": k, **v} for k, v in DEPOT_CATALOG.items()]
        )

        records = []
        start_dt = self.base_date + timedelta(days=start_offset_days)

        for day_idx in range(days):
            current_dt = start_dt + timedelta(days=day_idx)
            day_of_week = current_dt.weekday()  # 0 = Monday, 6 = Sunday
            day_of_year = current_dt.timetuple().tm_yday
            date_str = current_dt.strftime("%Y-%m-%d")

            # Day of week rhythm: operational surge mid-week (Tue-Thu), routine weekends
            dow_multiplier = 1.0 + 0.05 * math.sin(day_of_week * (2 * math.pi / 7))

            # Annual winter seasonality (surges in Oct-Jan, peaks in Dec)
            seasonal_wave = math.sin((day_of_year - 240) * (2 * math.pi / 365))

            for sku in sku_list:
                base_cons = sku["base_daily"]
                std_dev = base_cons * sku["std_dev_ratio"]
                season_factor = sku["seasonal_factor"]

                for depot in depot_list:
                    depot_weight = depot["weight"] if depot_id == "all" else 1.0

                    # Compute synthetic demand with seasonal wave and Gaussian noise
                    trend_adj = 1.0 + (day_idx * 0.0003)
                    seasonal_adj = 1.0 + (season_factor * seasonal_wave)

                    noise = rng.gauss(0, std_dev * depot_weight)
                    daily_val = (base_cons * depot_weight * dow_multiplier * seasonal_adj * trend_adj) + noise
                    demand = max(0.0, round(daily_val, 2))

                    records.append({
                        "date": date_str,
                        "timestamp": current_dt,
                        "item_id": sku["item_id"],
                        "item_name": sku["name"],
                        "category": sku["category"],
                        "location_id": depot["id"],
                        "location_name": depot["name"],
                        "unit": sku["unit"],
                        "demand": demand,
                        "is_synthetic": True,
                        "data_source": "synthetic",
                    })

        df = pd.DataFrame(records)
        df.sort_values(by=["timestamp", "item_id", "location_id"], inplace=True)
        df.reset_index(drop=True, inplace=True)
        return df

    def generate_aggregated_demand_series(
        self,
        item_id: str = "SKU-POL-DSL-01",
        depot_id: str = "all",
        days: int = 90,
        start_offset_days: int = -90,
    ) -> pd.DataFrame:
        """
        Generates daily demand aggregated by date for the selected SKU and depot filter.

        Returns:
            pd.DataFrame with columns ['date', 'timestamp', 'demand', 'is_synthetic', 'data_source']
        """
        df_raw = self.generate_daily_demand_series(
            item_id=item_id,
            depot_id=depot_id,
            days=days,
            start_offset_days=start_offset_days,
        )

        agg_df = (
            df_raw.groupby(["date", "timestamp"], as_index=False)["demand"]
            .sum()
            .sort_values(by="timestamp")
            .reset_index(drop=True)
        )
        agg_df["is_synthetic"] = True
        agg_df["data_source"] = "synthetic"
        return agg_df


# Module singleton instance
demand_generator = SyntheticDemandGenerator()
